// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:smsforward/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChannelTypeAdapter());
    registerAdapter(DiscordChannelAdapter());
    registerAdapter(EmailChannelAdapter());
    registerAdapter(FilterAdapter());
    registerAdapter(InstalledAppAdapter());
    registerAdapter(KeywordMatchTargetAdapter());
    registerAdapter(SlackChannelAdapter());
    registerAdapter(SmsChannelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChannelTypeAdapter());
    registerAdapter(DiscordChannelAdapter());
    registerAdapter(EmailChannelAdapter());
    registerAdapter(FilterAdapter());
    registerAdapter(InstalledAppAdapter());
    registerAdapter(KeywordMatchTargetAdapter());
    registerAdapter(SlackChannelAdapter());
    registerAdapter(SmsChannelAdapter());
  }
}
